In [10]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
from tictac_model import TicTacModel

import numpy as np

import random

import gymnasium

In [12]:
game = TicTacModel()

game.play(0,0)
game.play(1,1)
game.play(0,1)
game.play(2,2)
game.play(0,2)
if game.check_winner():
    print(f"{game.get_winner()} won")




1 won


In [13]:
game2 = TicTacModel()

while game2.turns < 9:
    game2.play(random.randint(0,2), random.randint(0,2))
    if game2.check_winner():
        print(f"{game2.get_winner()} won")
        break

1 won


In [21]:
# import copy

game3 = TicTacModel()

game3.play(0,0)
game3.play(1,1)
game3.play(0,1)
# game3.play(1,2)


print(game3)
print(game3.tree())

print(game3.trees)


[[ 1  1  0]
 [ 0 -1  0]
 [ 0  0  0]]
-1
False
1
934


In [19]:
5*4*3*2

120