# Reinforcement Learning - Lab 3
### J. Martinet

## Find $\pi*$ for TicTacToe using DP


Check [https://medium.com/@nour.oulad.moussa/tic-tac-toe-with-reinforcement-learning-part-i-markov-decision-process-value-policy-iteration-c4bcbb0b9fbe] for help.


In [1]:
%load_ext autoreload
%autoreload 2

%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
# Your code here

import numpy as np
import random
import sys

sys.path.append('../lab1')

try:
    from ..lab1.tictac_model import TicTacModel
except ImportError:
    from tictac_model import TicTacModel



In [6]:
game = TicTacModel()


In [7]:
game.play(0, 0)
game.play(0, 1)
# game.play(1, 1)
# game.play(1, 0)
print(game)
game.tree()

[[ 1 -1  0]
 [ 0  0  0]
 [ 0  0  0]]
1
False


0.7285714285714286

In [11]:
game.play()

TypeError: TicTacModel.play() missing 2 required positional arguments: 'x' and 'y'